### ISSUE TITLE
设置啊噗噗无法使用

### ISSUE THREAD

**Issue by jaclla** [QiuChenlyOpenSource/91QiuChen#27]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

设置啊噗噗里面下载的软件无法打开
![WX20240308-112738](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/34511671/119d6e81-100d-4f93-bf28-8c3522bbf942)
未能完成操作。（.error错误1701。）

### 最小复现

打开软件就报错未能完成操作。（.error错误1701。）

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
os:mac apple
```

### 期望行为

能正常使用设置啊噗噗下载安装的软件

**Comment by jaclla** [comment]
关闭了，设置啊噗噗下载安装后还是要跑一下脚本就可以用了。

**Comment by 4332weizi** [comment]
@jaclla 请问跑的是注入脚本吗？我跑了之后还是1701错误
