### ISSUE TITLE
Downie 4注入后异常

### ISSUE THREAD

**Issue by ttbug** [QiuChenlyOpenSource/91QiuChen#29]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

测试发现Downie 4 无法激活，版本为4.7.5

### 最小复现

注入后，打开软件，弹出崩溃窗口

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
macos 14.0
cpu m1 pro
memory 32G
```

### 期望行为

程序能正常打开使用

### 额外信息

从应用程序右键启动，程序仍崩溃无法使用

### Crash Log

Failed to get application state - fetching it resulted in an exception API misuse: modification of a menu's items on a non-main thread when the menu is part of the main menu. Main menu contents may only be modified from the main thread..

Uncaught system exception: signal 5

0   XUCore                              0x00000001014fc3a0 $s6XUCore18XUStacktraceStringSSyF + 44
1   DownmuteUI                          0x0000000100aecdbc __swift_memcpy48_8 + 9896
2   DownmuteUI                          0x0000000100aebfb4 __swift_memcpy48_8 + 6304
3   ExceptionHandling                   0x00000001a7cc1ab8 -[NSExceptionHandler _handleException:mask:] + 312
4   ExceptionHandling                   0x00000001a7cc1868 NSExceptionHandlerUncaughtSignalHandler + 44
5   libsystem_platform.dylib            0x00000001854a9a24 _sigtramp + 56
6   XUCore                              0x00000001014e728c $s6XUCore23XUSynchronousDataLoaderC04loadC0AC8ResponseVyKF + 180
7   XUCore                              0x00000001014c8ac4 $s6XUCore16XUDownloadCenterC12downloadData4with10Foundation0E0VAF10URLRequestV_tKF + 656
8   XUCore                              0x00000001014c98c0 $s6XUCore16XUDownloadCenterC15downloadWebPage2at17preferredEncoding15requestModifierSS10Foundation3URLV_SSAHE0I0VSgyAH10URLRequestVzcSgtKF + 276
9   DownieCore                          0x00000001038cbfd4 $s10DownieCore12XUDownloaderC14downloadSource2at2asAA08XUParsedE0V10Foundation3URLV_AH6FormatOtKF + 216
10  DownieCore                          0x0000000103a7e434 $s10DownieCore21XUDownloadsControllerC19ProcessingOperationC4mainyyF + 196
11  DownieCore                          0x0000000103a7e728 $s10DownieCore21XUDownloadsControllerC19ProcessingOperationC4mainyyFTo + 24
12  Foundation                          0x00000001866417c0 __NSOPERATION_IS_INVOKING_MAIN__ + 16
13  Foundation                          0x0000000186640b68 -[NSOperation start] + 648
14  Foundation                          0x00000001866408d8 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
15  Foundation                          0x00000001866407c8 __NSOQSchedule_f + 172
16  libdispatch.dylib                   0x00000001852dc860 _dispatch_block_async_invoke2 + 148
17  libdispatch.dylib                   0x00000001852cd910 _dispatch_client_callout + 20
18  libdispatch.dylib                   0x00000001852d0dc8 _dispatch_continuation_pop + 600
19  libdispatch.dylib                   0x00000001852d03e4 _dispatch_async_redirect_invoke + 584
20  libdispatch.dylib                   0x00000001852df1f4 _dispatch_root_queue_drain + 392
21  libdispatch.dylib                   0x00000001852dfa04 _dispatch_worker_thread2 + 156
22  libsystem_pthread.dylib             0x00000001854770d8 _pthread_wqthread + 228
23  libsystem_pthread.dylib             0x0000000185475e30 start_wqthread + 8

**Comment by X1a0He** [comment]
该问题已在最新版中修复，请更新库并重新拉取
<img width="876" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/43105322/5c50d44c-bf05-4621-955a-5d782ef7b963">
