### ISSUE TITLE
心愿列表

### ISSUE THREAD

**Issue by erik-bershely** [QiuChenlyOpenSource/91QiuChen#3]
App名字：setapp-istat
应用简单介绍：是一款 macOS 上的系统监控工具，它的作用是提供用户实时监控系统的性能指标，比如 CPU 使用率、内存占用、网络活动等等。
是否有破解版：有
应用链接：https://store.setapp.com/app/144/9607/app-1704331143-6596078754af6.zip

**Comment by erik-bershely** [comment]
App名字：setapp-XCOrganizer
应用简单介绍：XCOrganizer 是一个可以让您轻松找到磁盘上任何项目的工具。 浏览按类型分组的 Xcode 项目、Xcode 工作区、Swift Playgrounds 和 Swift 包。 根据项目目标分配标签。 将您正在处理的任何内容添加到收藏夹。 人类不可能跟踪所有项目名称。 XC组织者可以。
是否有破解版：无
应用链接：https://store.setapp.com/app/407/8157/app-1685704795-6479d05b0e326.zip

**Comment by llewis0** [comment]
App名字：mediamate
应用简单介绍：MediaMate 为音量、显示屏和键盘亮度 HUD 提供了全新的视觉效果，并引入了全新的正在播放 HUD，可以无需键盘更快捷地调整音量、亮度、控制正在播放等。
是否有破解版：无
应用链接：https://wouter01.github.io/MediaMate/

**Comment by llewis0** [comment]
> App名字：mediamate 应用简单介绍：MediaMate 为音量、显示屏和键盘亮度 HUD 提供了全新的视觉效果，并引入了全新的正在播放 HUD，可以无需键盘更快捷地调整音量、亮度、控制正在播放等。 是否有破解版：无 应用链接：https://wouter01.github.io/MediaMate/
> 
> 回复： 已完整破解。

感谢！！

**Comment by everbef0re** [comment]
App名字：StarUML
应用简单介绍：一个成熟的软件建模器，用于敏捷和简洁的建模
是否有破解版：有（但最新的major版本没有）
应用链接：https://staruml.io/

**Comment by n0vemB** [comment]
app名称：Remote Buddy
应用介绍：一款通过iPhone、iPad、Apple TV等来控制Mac的App，可以模拟键盘、鼠标、遥控器操作Mac，支持睡眠唤醒、屏幕共享、流媒体控制，独立控制100多个app等等。
是否有破解版：有（但是几年前的版本破解，已无法兼容新版，破解组也没有进行更新）
下载地址：https://get.remotebuddy.app/

**Comment by TrustDec** [comment]
PDF Reader Pro
应用介绍：PDF Reader Pro是一款Mac平台的PDF文档阅读编辑器，除了可以进行 PDF 文档阅读以外，你还可以对文档进行备注、编辑、标注等，还可以添加笔记和书签，如果想要演示的话，还可以配合遥控来进行演示。
是否有破解版：有
下载地址：https://xclient.info/s/pdf-reader-pro.html
官网：https://www.pdfreaderpro.com

**Comment by WPF0414** [comment]
> 应用名称：StarUML 应用简单介绍：一个成熟的软件建模器，用于敏捷和简洁的建模 是否有破解版本：有（但最新的主要版本没有） 应用链接：https://staruml.io/

已完整破解。

**Comment by WPF0414** [comment]
> 应用名称：StarUML 应用简单介绍：一个成熟的软件建模器，用于敏捷和简洁的建模 是否有破解版本：有（但最新的主要版本没有） 应用链接：https://staruml.io/

已完整破解。tools/StarUML执行main.py

**Comment by everbef0re** [comment]
> > 应用名称：StarUML 应用简单介绍：一个成熟的软件建模器，用于敏捷和简洁的建模 是否有破解版本：有（但最新的主要版本没有） 应用链接：https://staruml.io/
> 
> 已完整破解。tools/StarUML执行main.py

🐮的，thx

**Comment by TrustDec** [comment]
MacCleaner Pro
应用介绍：Professional tools for Mac cleanup Keep your Mac always fast, clean and organized
是否有破解版：无
官网：https://nektony.com/mac-cleaner-pro

**Comment by OceanApart** [comment]
# MarginNote 3

> 全新上线电子阅读器，助力更高效书籍阅读和学习。革新性整合阅读标注工具，思维导图和学习卡，多维度构建知识连接，提升阅读学习生产力。

- 是否有破解版：无。网上流传的都是四年前的旧版本 3.5.9。
- 下载链接：https://store.setapp.com/app/144/9607/app-1704331143-6596078754af6.zip
- 官网：https://s.marginnote.cn/x

**Comment by DemonJun** [comment]
Xterminal
应用介绍：不仅是强大的SSH工具，更提供本地控制台，以及更多即将推出的开发相关功能，让您专注于创造卓越的代码
是否有破解版：无
官网：https://www.xterminal.cn

**Comment by X1a0He** [comment]
> MacCleaner Pro 应用介绍：Professional tools for Mac cleanup Keep your Mac always fast, clean and organized 是否有破解版：无 官网：https://nektony.com/mac-cleaner-pro

回复：
已完整破解。
[#16](https://github.com/QiuChenlyOpenSource/91QiuChen/pull/16)

**Comment by tpnet** [comment]
App名字：剪映专业版
应用简单介绍：是字节系的一款 macOS 上的视频编辑软件。
是否有破解版：无
应用链接：https://www.capcut.cn/

**Comment by X1a0He** [comment]
> # MarginNote 3
> > 全新上线电子阅读器，助力更高效书籍阅读和学习。革新性整合阅读标注工具，思维导图和学习卡，多维度构建知识连接，提升阅读学习生产力。
> 
> ![preview 1](https://camo.githubusercontent.com/86af26ff8fc3c525d7c180b69652c795bb944b76d6a1913cc4bb2440eebaec17/68747470733a2f2f6973312d73736c2e6d7a7374617469632e636f6d2f696d6167652f7468756d622f507572706c653131342f76342f32322f36622f35342f32323662353465322d613330662d316634632d353066652d6262313832643233313035372f39363330656135632d663435382d346439632d623536302d3632323865656465356431315f392e376368315f55373638345f55353236665f55363732632e706e672f3632367830772e77656270)
> 
> * 是否有破解版：无。网上流传的都是四年前的旧版本 3.5.9。Setapp 里的破解后也不能打开
>   
>   * <img alt="image" width="255" src="https://private-user-images.githubusercontent.com/19257940/307656533-b0176ab2-65e3-4dbc-b5a2-069acc57e6b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDEzODgsIm5iZiI6MTcwOTA0MTA4OCwicGF0aCI6Ii8xOTI1Nzk0MC8zMDc2NTY1MzMtYjAxNzZhYjItNjVlMy00ZGJjLWI1YTItMDY5YWNjNTdlNmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEzMzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOThmYWIxNzVlMWQyMTEwZDUyMTdjYzU4YWU2MzMwZDdkNGFkYjg5YjYxOTc5MzUyNmEwNzNmMmNiMGRkZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Stn750EuVQYxHZIZWPuRfllWISLiZXp85f0O4G0UVrM">
> * 下载链接：https://store.setapp.com/app/144/9607/app-1704331143-6596078754af6.zip
> * 官网：https://s.marginnote.cn/x

回复：
已完整破解。
https://github.com/QiuChenlyOpenSource/91QiuChen/pull/17

**Comment by fhefh2015** [comment]
App名字：Screen Studio
应用简单介绍：能够以全自动的方式，在录屏的时候，根据鼠标的移动轨迹，自动加入缩小，放大，平移等操作
是否有破解版：无
官网：https://www.screen.studio/

**Comment by Nuoyancv** [comment]
App名字：termius
应用简单介绍：很方便的SSH管理工具，但是不是pro版本不能进行端口转发。
是否有破解版：有
官网：https://termius.com/

**Comment by DreamingloveR** [comment]
App名字：Heptabase
应用简单介绍：一款白板与思维导图相结合的视觉化笔记软件。
是否有破解版：无
应用链接：https://heptabase.com/download

**Comment by laofun** [comment]
App名字：setapp-Proxyman
应用简单介绍：A Native web debugging proxy app
是否有破解版：有
应用链接：https://store.setapp.com/app/346/9867/app-1707967407-65cd83af39363.zip

**Comment by barbara012** [comment]
App名字：Sip
应用简单介绍：Sip 是一款现代色彩拾取器，可轻松实现色彩组织和团队协作。
是否有破解版：有（但是不好用）
应用链接：https://sipapp.io/downloading/
官网：https://sipapp.io/

**Comment by geek4what** [comment]
App名字：PopClip
应用简单介绍：PopClip appears when you select text in any app, giving you instant access to useful actions.
是否有破解版：有
官网：https://www.popclip.app/

**Comment by Bssn520** [comment]
App名字：FinalShell
应用简单介绍：FinalShell是一体化的的服务器,网络管理软件,不仅是ssh客户端,还是功能强大的开发,运维工具,充分满足开发,运维需求.
是否有破解版：无
官网：https://www.hostbuf.com/
下载地址：https://www.hostbuf.com/t/988.html

**Comment by biggding** [comment]
App名字：BetterDisplay
应用简单介绍：非常好用的多显示器管理工具
是否有破解版：无
官网：https://github.com/waydabber/BetterDisplay#readme
下载地址：https://github.com/waydabber/BetterDisplay/releases

**Comment by GHA193** [comment]
App名字：Genymotion Desktop
应用简单介绍：是一款跨平台的安卓模拟器，支持Android 13.
是否有破解版：无mac版破解
应用链接：https://www.genymotion.com/product-desktop/download/

**Comment by tpnet** [comment]
> App名字：Genymotion Desktop 应用简单介绍：是一款跨平台的安卓模拟器，支持Android 13. 是否有破解版：无mac版破解 应用链接：https://www.genymotion.com/product-desktop/download/

Mumu现在可以先平替一下。

**Comment by GHA193** [comment]
> > App名字：Genymotion Desktop 应用简单介绍：是一款跨平台的安卓模拟器，支持Android 13. 是否有破解版：无mac版破解 应用链接：https://www.genymotion.com/product-desktop/download/
> 
> Mumu现在可以先平替一下。

mumu版本太低了，Android 6😂

**Comment by CooperZhuang** [comment]
App名字：wins
应用简单介绍：是一款为Mac带来系统级的分屏功能的工具。
是否有破解版：有，三个月前的1.6.5，不知为啥失效在自己电脑失效了，现在最新的是 1.6.6
应用官网：https://wins.cool/html/index_zh.html?lang=zh
应用链接（官方只能下到 1.6.4 版本）：https://us.softpedia-secure-download.com/dl/4d7772e2070f2c3a060bd9f48c5847ad/65ea8a61/400143222/mac/System-Utilities/Wins-latest.dmg

**Comment by TrustDec** [comment]
App名字：TeamViewer
应用简单介绍：TeamViewer是一个能在任何防火墙和NAT代理的后台用于和文件传输的简单且快速的解决方案。为了连接到另一台计算机，只需要在两台计算机上同时运行 TeamViewer 即可，而不需要进行安装（也可以选择安装，安装后可以设置开机运行）。该软件第一次启动在两台计算机上自动生成伙伴 ID。只需要输入你的伙伴的ID到TeamViewer，然后就会立即建立起连接。
应用官网：https://www.teamviewer.com/en-in/
应用链接：https://us.softpedia-secure-download.com/dl/4d7772e2070f2c3a060bd9f48c5847ad/65ea8a61/400143222/mac/System-Utilities/Wins-latest.dmg

**Comment by BailinSong** [comment]
App名字：royal tsx
应用简单介绍：一款功能非常强大适用于 Mac 的远程连接管理工具。兼容多种连接类型,比如:RDP、VNC、基于SSH连接的终端,SFTP/FTP/SCP或基于Web的连接管理
是否有破解版：是
应用链接：https://royaltsx-v6.royalapps.com/updates/royaltsx_6.0.2.1000.dmg

**Comment by Nuoyancv** [comment]
> App名字：termius 应用简单介绍：很方便的SSH管理工具，但是不是pro版本不能进行端口转发。 是否有破解版：有 官网：https://termius.com/
> 
> https://github.com/QiuChenlyOpenSource/91QiuChen/tree/main/tool/terminus_zh_CN 看得懂就看 看不懂拉倒

牛逼，可以了

**Comment by hachikozjq** [comment]
App名字：DbSchema
应用简单介绍：数据库模型ER关系建立软件
是否有破解版：否
应用链接：https://dbschema.com/

**Comment by DangerYu89** [comment]
PD虚拟机，谢谢。

**Comment by QiuChenly** [comment]
> PD虚拟机，谢谢。

由于强力的反盗版措施，在SIP ON下我做不到像以前一样无痛使用，所以一直没有更新。有需要自己用19.1配合补丁使用

**Comment by sakunoo** [comment]
App名字：Moment
应用简单介绍：Moment是一个基于菜单栏和通知中心的倒计时应用，帮助你记住生活中最值得纪念的日子。
是否有破解版：否
应用链接：https://fireball.studio/moment/download

**Comment by liszt188** [comment]
App名字：Anybox
应用简单介绍：Anybox-跨平台书签管理及稍后读。轻松保存和整理链接，还支持保存便条和图片，知识管理必备。
是否有破解版：否
应用链接：https://anybox.app/zh-CN
下载地址：https://apps.apple.com/cn/app/id1593408455

**Comment by QiuChenly** [comment]
> App名字：Moment 应用简单介绍：Moment是一个基于菜单栏和通知中心的倒计时应用，帮助你记住生活中最值得纪念的日子。 是否有破解版：否 应用链接：https://fireball.studio/moment/download

https://qiuchenlyopensource.github.io/Documentaions/%E4%BB%8B%E7%BB%8D.html#apps

**Comment by QiuChenly** [comment]
> Xterminal 应用介绍：不仅是强大的SSH工具，更提供本地控制台，以及更多即将推出的开发相关功能，让您专注于创造卓越的代码 是否有破解版：无 官网：https://www.xterminal.cn

![image](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/24793281/67728dbe-3891-4516-8dde-13d48e01f9d2)
吊用没有，懒得发。

**Comment by QiuChenly** [comment]
> App名字：Anybox 应用简单介绍：Anybox-跨平台书签管理及稍后读。轻松保存和整理链接，还支持保存便条和图片，知识管理必备。 是否有破解版：否 应用链接：https://anybox.app/zh-CN 下载地址：https://apps.apple.com/cn/app/id1593408455

没有iOS设备同步，并且我是Android手机，评价为阮用没有，懒得弄。

**Comment by QiuChenly** [comment]
> royal tsx

实际使用下来，那些插件功能软用没有，真不如Termius. 长的也丑，懒得弄。

**Comment by bfchengnuo** [comment]
App：SSH Config Editor
介绍：以智能、高效的方式管理您的 SSH 客户端配置文件。
破解版：有
地址：https://hejki.tilda.ws/ssheditor

**Comment by BailinSong** [comment]
> > Xterminal 应用介绍：不仅是强大的SSH工具，更提供本地控制台，以及更多即将推出的开发相关功能，让您专注于创造卓越的代码 是否有破解版：无 官网：https://www.xterminal.cn
> 
> ![image](https://private-user-images.githubusercontent.com/24793281/313136871-67728dbe-3891-4516-8dde-13d48e01f9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2Njg5MTYsIm5iZiI6MTcxMDY2ODYxNiwicGF0aCI6Ii8yNDc5MzI4MS8zMTMxMzY4NzEtNjc3MjhkYmUtMzg5MS00NTE2LThkZGUtMTNkNDhlMDFmOWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA5NDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZGI1NjBiZmQ0ZWE4YzFlMGZkNGY1ZWJhMzM2NDMxNWQ3Y2ViZmU1NTIyY2U5M2M4M2Q4MTQ4YzJiNDE3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H0K1EqERsmZDVIS6g7CjvoaJBMlY1Yh5QjYZmcT9_EM) 吊用没有，懒得发。

4090 显卡驱动起来了么？ 支持mps 么？

**Comment by fhefh2015** [comment]
App名字：FocuSee
应用简单介绍：能够以全自动的方式，在录屏的时候，根据鼠标的移动轨迹，自动加入缩小，放大，平移等操作
是否有破解版：无
官网：https://gemoo.com/focusee/index.htm

**Comment by zjns** [comment]
> > > App名字：Genymotion Desktop 应用简单介绍：是一款跨平台的安卓模拟器，支持Android 13. 是否有破解版：无mac版破解 应用链接：https://www.genymotion.com/product-desktop/download/
> > 
> > 
> > Mumu现在可以先平替一下。
> 
> mumu版本太低了，Android 6😂

mumu pro基于Android 12，

> > > App名字：Genymotion Desktop 应用简单介绍：是一款跨平台的安卓模拟器，支持Android 13. 是否有破解版：无mac版破解 应用链接：https://www.genymotion.com/product-desktop/download/
> > 
> > 
> > Mumu现在可以先平替一下。
> 
> mumu版本太低了，Android 6😂

mumu pro基于Android 12，mitm就可以一直用了

**Comment by llewis0** [comment]
App名字：Lunar
应用简单介绍：是一款非常实用的 macOS内置/外接显示器调节控制软件。
是否有破解版：有（旧版本），之前用surge module能激活但是试了下好像失效了呢。
应用链接：https://lunar.fyi

**Comment by fmz200** [comment]
App名字：Parallels Toolbox for Mac
应用简单介绍：Parallels Toolbox for Mac是一款非常实用的 macOS 状态栏小工具，其中提供了 40 多种适用于 macOS和 Windows 的工具。如下图。
是否有破解版：有，但目前仅支持到版本6.0.2，现最新版本为6.6.2
应用链接：https://www.parallels.cn/products/toolbox/
工具列表：
![image](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/57740735/f2a989ec-7472-4896-85d9-2c55b5d84f65)
![image](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/57740735/84a5e709-fdf4-4569-b392-1f9e1b57f735)

**Comment by JOJOforshaun** [comment]
App名字：OlivedPro
应用简单介绍：OlivedPro 是一款现代化的全平台直播录像机，它会时刻监控主播的直播状态，并在您喜欢的主播上线时自动开启录制。帮助您捕捉每一个直播内容，就像普通的电视录像机一样。
OlivedPro 可以以最佳视频质量进行录制，从 720p 到 4K！在您的网络带宽允许的情况下，它可以同时录制任意场直播。现在，OlivedPro 已支持录制 Youtube、Twitch、Tiktok、抖音、斗鱼、虎牙、Nimo 、Bilibili 等平台！

高级版

需要激活许可证
可同时录制任意场直播
最高的视频质量（HD+）
直播开始时自动开启录制
自动保存观看列表
自动 mp4 重新编码
是否有破解版：无
应用链接：https://olived.app/zh-Hans/

**Comment by QiuChenly** [comment]
![Screenshot_2024-03-25-08-33-20-540_tw nekomimi nekogram](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/24793281/85054af8-090c-4974-b084-f3bda49c2d95)

关闭原因
自己找别人求去吧 反正都捡谁赏吃的不是吃啊
