### ISSUE TITLE
设置啊噗噗版本的aldente无法安装辅助程序，不能正常使用

### ISSUE THREAD

**Issue by baker221** [QiuChenlyOpenSource/91QiuChen#32]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

Aldente Pro 1.25.2 啊噗噗版本；能成功破解和打开，但是安装辅助程序一直没生效，
<img width="426" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/43471538/fad29d7b-f0e7-478d-ad27-886ad281c800">

### 最小复现

打开上述软件，显示上面截图的图像，选打开设置，重新安装后依然如此

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
M2 MacBook Air; macOS 12.7.3
```

### 期望行为

软件能正常运行并使用

**Comment by QiuChenly** [comment]
这个app我也不太清楚，请xiaohe处理一下吧 @X1a0He

**Comment by X1a0He** [comment]
现已支持官方版Aldente Pro，请到官网进行下载官方版本，久等
<img width="280" alt="AlDente Helper" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/43105322/a7086c84-faf4-4923-8739-f17ae14c371a">
<img width="452" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/43105322/09448c88-52f0-48c6-bbe7-0410dd164905">
