### ISSUE TITLE
surge 5.5.0的脚本无法生效

### ISSUE THREAD

**Issue by adntian** [QiuChenlyOpenSource/91QiuChen#33]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

最近使用了surge的5.5.0的两个版本（2586/2589），发现脚本无法工作，测试了2个部分的脚本

surge的2586和2589版本使用对应的Inject进行注入，尝试重新安装过mitm证书

切换回5.4.4版本使用均正常
（另外网关模式下，使用时间久了好像会存在类似假死的情况，下游设备无法上网，重新reload配置方可恢复，这个问题暂时还在定位中，可忽略，下图是网关模式日志）
![image](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/2285733/7830305b-5e73-4ee8-8eef-a7c57f3e2f4e)

### 最小复现

1. ”模块“下的脚本，使用[Sub-Stroe模块](https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/config/Surge.sgmodule)后，无法打开[https://sub.store](https://sub.store)
2. “脚本”功能下，写js脚本后会报脚本中止

以下是脚本执行时的请求查看器中脚本日志：
> 11:02:15.684516 [Connection] Incoming proxy protocol: HTTP
11:02:15.684747 [MITM] MITM over HTTP/2
11:02:15.685353 [Script] HTTP request script found: Sub-Store Simple
11:02:15.709904 [Connection] Disconnect with reason: Script abort

在surge的日志中报错如下（版本5.5.0 (2589)）：
> 2024-03-22 11:06:56.977947 <WARNING> [SGAssert] Assert failed! [SGJSVM] SGJSVM.m:478, -[SGJSVM _loadLib] _lib
2024-03-22 11:06:56.982673 <WARNING> [SGLogger] Call stack: (
	0   Surge                               0x0000000104e172b6 Surge + 737974
	1   Surge                               0x0000000104e1723e Surge + 737854
	2   Surge                               0x0000000104e177bf Surge + 739263
	3   Surge                               0x000000010501ecb0 Surge + 2866352
	4   Surge                               0x000000010501e748 Surge + 2864968
	5   Surge                               0x0000000104ee19b5 Surge + 1567157
	6   libdispatch.dylib                   0x00007ff8104722e6 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x00007ff81047359a _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007ff81047f8e1 _dispatch_main_queue_drain + 993
	9   libdispatch.dylib                   0x00007ff81047f4f2 _dispatch_main_queue_callback_4CF + 31
	10  CoreFoundation                      0x00007ff81073710a __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x00007ff8106f6700 __CFRunLoopRun + 2463
	12  CoreFoundation                      0x00007ff8106f5799 CFRunLoopRunSpecific + 557
	13  HIToolbox                           0x00007ff81b4ad9d9 RunCurrentEventLoopInMode + 292
	14  HIToolbox                           0x00007ff81b4ad7e6 ReceiveNextEventCommon + 665
	15  HIToolbox                           0x00007ff81b4ad531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
	16  AppKit                              0x00007ff813c67c39 _DPSNextEvent + 880
	17  AppKit                              0x00007ff814571804 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
	18  AppKit                              0x00007ff813c591b2 -[NSApplication run] + 603
	19  AppKit                              0x00007ff813c2d1c1 NSApplicationMain + 816
	20  Surge                               0x00000001050304a3 Surge + 2938019
	21  dyld                                0x000000020569c386 start + 1942
), slide 0x4d63000 load addr 0x104d63000, queue com.apple.main-thread
2024-03-22 11:06:56.991432 <WARNING> [SGJSVM] Failed to update SGJSVM lib: (null) Error Domain=KDSimpleError Code=0 "decrypt failed" UserInfo={NSLocalizedDescription=decrypt failed}

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
测试过的系统：
MackBook M1 Pro
OS: 14.3.1
CPU: M1Pro
Memery: 16G

MacMini M1 (启用了SIP，当作网关模式）
OS: 14.3.1
CPU: M1
Memery: 8G
```

### 是否修改了nvram的内核启动参数（黑苹果）

否

### 是否使用了需要修改系统文件的工具（黑苹果）

否

### 期望行为

有空了可以看一下问题

**Comment by QiuChenly** [comment]
Engine=jsc.
第二，我不用模块，用不了关我屁事。
