### ISSUE TITLE
Office 16.83 离线使用闪退，联网正常

### ISSUE THREAD

**Issue by bfchengnuo** [QiuChenlyOpenSource/91QiuChen#34]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

连接 Wi-Fi 使用是正常的，断网使用就会闪退，断网后 word 里打几个字就崩了，
![image](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/16206117/69b20509-0a92-479c-8b6d-180df38d1885)

### 最小复现

关闭 Wi-Fi，打开 word，闪退

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS：14.3.1
CPU：Intel
```

### 期望行为

离线工作正常

### 额外信息

PPT 可能存在同样问题。

**Comment by QiuChenly** [comment]
没有日志

**Comment by bfchengnuo** [comment]
秋佬这个日志是 Word 崩溃的那个详细信息吗？控制台里的崩溃报告没看到 Word 相关的。

[Microsoft Error Reporting log version- 2.0.log](https://github.com/QiuChenlyOpenSource/91QiuChen/files/14744692/Microsoft.Error.Reporting.log.version-.2.0.log)
