### ISSUE TITLE
Table Plus 注入后异常

### ISSUE THREAD

**Issue by lvxianchao** [QiuChenlyOpenSource/91QiuChen#37]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

通过 Homebrew 安装的 Table Plus，版本为：`Version 5.9.6 (546)`。

<img width="350" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/22412818/5b80b6ab-b821-45d7-9a1b-50d68cf93242">

注入以后，打开 SQL 编辑器，输入 `select` 等 SQL 关键字以后，使用 `tab` 自动补全，出来的**关键字会被加上反引号** `：

<img width="222" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/22412818/080687e2-05fa-4578-9319-8035bf22095d">

**下图为正常的自动补全效果：**

<img width="188" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/22412818/f86e03f5-3ce6-450f-985c-b6a8ff53424c">

### 最小复现

1. 安装 TablePlus: `brew install tableplus`。
2. 随便建立一个数据库连接，打开 SQL 编辑器输入 `sel`，然后 `tab` 自动补全，此时为尚未注入状态，关键词等自动补全均为正常状态。
3. 注入，再次输入 `sel` 等，发现 SQL 关键词、表名等自动补全以后都会加上反引号 `。

### 系统情况

- [X] SIP 是否启动
- [X] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
型号名称：	Mac Pro
  型号标识符：	MacPro7,1
  处理器名称：	13th Gen Intel(R) Core(TM) i5-13600KF
  处理器速度：	3.5 GHz
  处理器数目：	1
  核总数：	14
  L2缓存：	20 MB
  L3缓存：	24 MB
  超线程技术：	已启用
  内存：	64 GB
  系统固件版本：	2020.0.1.0.0
  操作系统加载程序版本：	580~1053
```

### 是否修改了nvram的内核启动参数（黑苹果）

keepsyms=1 debug=0x100  alcid=11 agdpmod=pikera

### 是否使用了需要修改系统文件的工具（黑苹果）

没有使用

### 期望行为

输入 SQL 关键词、表名等自动补全以后不要使用反引号包起来。

### 额外信息

* 尝试过重新安装，没有效果，注入后就产生问题了。
* 尝试过直接从官网下载安装包，问题依旧。

### Crash Log

运行良好，没有崩溃。

**Comment by MrChenSH** [comment]
看看这个：https://github.com/marlkiller/dylib_dobby_hook

**Comment by X1a0He** [comment]
该问题已被定位且修复，等待更新即可，感谢您的反馈，祝你生活愉快
