### ISSUE TITLE
最新版adobe ps 25.6 无法注入！打开显示无数据注入。

### ISSUE THREAD

**Issue by junne14105** [QiuChenlyOpenSource/91QiuChen#39]
<img width="1397" alt="iShot_2024-04-04_09 08 24" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/112349113/3487a10b-0070-4c76-a62e-36751f110c9f">

还有希望在里面在添加一个软件的注入破解：set.a.light 3D

**Comment by X1a0He** [comment]
原神_启动已不再维护，如有Python环境，推荐使用 秋城落叶_启动.command
Arm 下 PS 25.6 测试正常
<img width="1076" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/43105322/5685740a-8d70-476f-8ba9-429155b7409d">
