### ISSUE TITLE
运行秋城落叶_启动.command失败

### ISSUE THREAD

**Issue by oneCatZz** [QiuChenlyOpenSource/91QiuChen#40]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

运行之后调用main.python时失败
![CleanShot 2024-04-06 at 22 10 11@2x](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/32626686/ecefe6a8-bb26-47d9-8bf8-7f25447ae3a9)

### 最小复现

当前python版本是3.11.5，运行秋城落叶_启动.command之后输入机器密码后就报错

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS：14.4.1 (23E224)
Memory：36G
ARM
```

### 期望行为

正常运行

**Comment by X1a0He** [comment]
抱歉，已修复，请拉取最新版进行使用
