### ISSUE TITLE
Bartender 5.0.49 失效

### ISSUE THREAD

**Issue by uclort** [QiuChenlyOpenSource/91QiuChen#43]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

运行完`秋城落叶_启动.command`之后，重启 Bartender(版本为 5.0.49)，首次弹出  QiuChen 的提示信息，进入设置`About`中还是显示试用状态，`License`中无信息。

![Xnip2024-04-11_09-40-42](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/17818831/fcd8e633-5198-4072-b38b-21add53b33de)
![CleanShot 2024-04-11 at 09 41 12](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/17818831/0b11dd9e-26b1-46dd-894a-82602ad5f3f2)

### 最小复现

和描述一致

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
已上传设备信息截图。
```

### 是否修改了nvram的内核启动参数（黑苹果）

无

### 是否使用了需要修改系统文件的工具（黑苹果）

无

### 期望行为

正常注入成功

### 额外信息

我已经尝试过使用`App Cleaner & Uninstaller`删除`Bartender`，并且在官网下载最新的安装包(5.0.49)

**Comment by uclort** [comment]
另外发现同一台设备上，**Xnip**商店最新版注入完重启 App，无法启动。

**Comment by QiuChenly** [comment]
xnip太古老了 建议换新的。至于Bartender 我还看不出来原因

**Comment by uclort** [comment]
> xnip太古老了 建议换新的。至于Bartender 我还看不出来原因

你好，换 iShot 之后显示授权给：秋城落叶，执行切图后弹窗试用期还剩下 0 天 0 小时，无法正常截图，下面是演示视频。

https://github.com/QiuChenlyOpenSource/91QiuChen/assets/17818831/db6a78d1-c87d-467a-a48f-94e244f6f613

**Comment by QiuChenly** [comment]
Bar下个提交修复，iShot这个问题我没研究，有空会弄。更新动态请关注tg频道。

**Comment by X1a0He** [comment]
最新库已支持Bartender 5.0.52
请点击链接后滑到最下面下载->[Bartender 5.0.52](https://www.macbartender.com/B2/updates/TestAppcastB5.xml)
