### ISSUE TITLE
Bob 注入成功还是有限制

### ISSUE THREAD

**Issue by ReaJason** [QiuChenlyOpenSource/91QiuChen#45]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

Bob 在 ARM 下，注入之后并不是 Pro 权限，翻译仍有次数限制，请问是没有支持 Pro 还是有 bug

![CleanShot 2024-04-14 at 11 46 55@2x](https://github.com/QiuChenlyOpenSource/91QiuChen/assets/48389642/dc9e1385-9c91-498f-b50d-b59a86c6135e)

### 最小复现

./秋城落叶_启动.command

在 Bob 的时候输入 y

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
Apple M3 Pro
14.4.1 (23E224)
18 GB
```

### 期望行为

无限制使用翻译

**Comment by QiuChenly** [comment]
这个确实存在问题 转译看看呢

**Comment by LeeeMooo** [comment]
先试用，再注入

**Comment by ReaJason** [comment]
> 先试用，再注入

感谢，这样好使了🌹
