### ISSUE TITLE
使用 Install.command 安装脚本时报错？

### ISSUE THREAD

**Issue by 52beta** [QiuChenlyOpenSource/91QiuChen#48]
Password:
Installation starts...
Progress: 82%2024-04-17 09:26:51.243 dvaPlistGen2016[2538:48940] CustomHook Started
2024-04-17 09:26:51.244 dvaPlistGen2016[2538:48940] CustomHook updating plist file, /Library/Preferences/com.Adobe.After Effects.paths.plist
Exit Code: 0          
﻿
Installation complete successfully!

**Comment by X1a0He** [comment]
都不知道哪来的这个文件

**Comment by 52beta** [comment]
Adobe Mac Script Installer 安装脚本，Adobe.After Effects 2024

**Comment by QiuChenly** [comment]
从哪下的去找谁 我仓库里有这个Install.command脚本？问问题也不看地方就提？
