### ISSUE TITLE
Surge注入后，不生效

### ISSUE THREAD

**Issue by izhaohuayu** [QiuChenlyOpenSource/91QiuChen#49]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

## 测试发现 Surge 5.6.1 皆无法激活

使用最新克隆的注入仓库
[🤔] [Surge] - [5.6.1] 是受支持的版本，是否需要注入？y/n(默认n)
y
开始注入App: com.nssurge.surge-mac
备份的原始文件已经存在,需要直接用这个文件注入吗？y/n(默认y)
n
Found FAT Header
Found thin header...
Found thin header...
Load command already exists
Successfully inserted a LC_LOAD_DYLIB command for x86_64
Load command already exists
Successfully inserted a LC_LOAD_DYLIB command for arm64
Writing executable to /tmp/app...
Attempting to resign /tmp/app...
/tmp/app: replacing existing signature

Successfully resigned executable
Need Deep Sign.
Found FAT Header
Found thin header...
Found thin header...
Inserting a LC_LOAD_DYLIB command for architecture: x86_64
Successfully inserted a LC_LOAD_DYLIB command for x86_64
Inserting a LC_LOAD_DYLIB command for architecture: arm64
Successfully inserted a LC_LOAD_DYLIB command for arm64
Writing executable to /Applications/Surge.app/Contents/Library/LaunchServices/com.nssurge.surge-mac.helper...
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.
No matching processes were found
rm: /Library/LaunchDaemons/com.nssurge.surge-mac.helper.plist: No such file or directory
rm: /Library/PrivilegedHelperTools/com.nssurge.surge-mac.helper: No such file or directory
/Applications/Surge.app/Contents/Library/LaunchServices/com.nssurge.surge-mac.helper: replacing existing signature
/Applications/Surge.app: replacing existing signature
Successfully reset All approval status for com.nssurge.surge-mac
App处理完成。

## 命令行启动程序
MacBook-Pro:91QiuChen root# /Applications/Surge.app/Contents/MacOS/Surge
2024-04-19 10:38:43.736 Surge[2782:55568] [Bugsnag] [INFO] Sent session DC9BA730-4326-4606-A0B6-F230369E78ED
2024-04-19 10:38:47.051 Surge[2782:55548] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.

### 最小复现

注入后打开截图
<img width="584" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/163373982/3d3e6a75-4344-45d5-b62e-9b7ebdb6394a">
点击 急了 后，还是需要激活

<img width="486" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/163373982/47b3759b-aa26-4232-a804-d6a6d2ebb1c7">

看现象是没有注入成功

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
本机信息：
System: MacBook Pro 16-inch, 2019
OS: macOS 14.4.1
CPU: 2.6 GHz 六核Intel Core i7
Memory: 32 GB 2667 MHz DDR4
SIP: off


```

### 期望行为

期望可以正常激活Surge

**Comment by jilulu** [comment]
Somehow they deleted surge support in commit 159fcc

**Comment by X1a0He** [comment]
Surge已不再支持.
Surge is no longer supported.
