### ISSUE TITLE
PD19注入后无法启动

### ISSUE THREAD

**Issue by JirachiZhang** [QiuChenlyOpenSource/91QiuChen#54]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

PD 版本19.1.0-54729，注入后无法启动
<img width="284" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/20529747/c3cfec9a-ff9f-471e-a9f6-00c9ef4a95d3">

### 最小复现

安装完 windows 镜像后，退出 PD 进行注入，显示破解成功。重新打开 PD 无法启动。

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
Intel i5
8G 内存
macOS 14.4.1
```

### 期望行为

期望可以正常启动

**Comment by QiuChenly** [comment]
重新安装后执行破解。

**Comment by JirachiZhang** [comment]
> 重新安装后执行破解。

使用App Cleaner & Uninstaller卸载并重新安装后依然如此。
已重复实验多次。

**Comment by QiuChenly** [comment]
不知道什么原因，我没遇到全新安装原始的版本还能起不了的。哦 我知道了 老款强制OpenCore Patcher升上来的就不要搁这问是不是补丁有问题，先想想自己是不是有问题。

**Comment by JirachiZhang** [comment]
> 不知道什么原因，我没遇到全新安装原始的版本还能起不了的。哦 我知道了 老款强制OpenCore Patcher升上来的就不要搁这问是不是补丁有问题，先想想自己是不是有问题。

OpenCore Legacy Patcher 升级mac os？我不是啊。我是20年的13寸mbp正常升级的。

**Comment by QiuChenly** [comment]
你这个很奇怪 既然不是这个问题的话 那我建议你看下操作步骤，我这里macOS 14 Intel SIP ON没有遇到问题。

**Comment by QiuChenly** [comment]
已经确认问题，请等待稍后的修复提交。

**Comment by JirachiZhang** [comment]
测试成功启动~
