### ISSUE TITLE
terminus_zh_CN运行报错。

### ISSUE THREAD

**Issue by InTheManXG** [QiuChenlyOpenSource/91QiuChen#55]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

在跑完了代码之后，显示报错。
<img width="662" alt="image" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/61611989/467ddd3e-8821-4831-8af7-def6a657dcd4">

### 最小复现

运行脚本，在跑完找到了 xxx，替换了 xxx 之后，显示上图中的错误信息。app.asar文件已经自动备份，但是跑完脚本之后，依然未中文，没有任何改变。

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
芯片 Apple M1 Pro 
内存 16 GB
macOS 14.4.1（23E224）
```

### 期望行为

希望可以完成这个软件的汉化。

### Crash Log

Traceback (most recent call last):
  File "/Users/inthemanxg/Downloads/91QiuChen-main/tool/terminus_zh_CN/cn.py", line 83, in <module>
    main()
  File "/Users/inthemanxg/Downloads/91QiuChen-main/tool/terminus_zh_CN/cn.py", line 67, in main
    with open(fileOut, "w", encoding="utf-8") as u:
PermissionError: [Errno 13] Permission denied: '/Applications/Termius Beta.app/Contents/Resources/app/background-process/assets/index-90a0e652.js'

**Comment by QiuChenly** [comment]
英语三级没过？
Permission denied 翻译一下也知道是没权限写入文件的意思了啊
就一个读写权限你都会跑python了加个sudo很难吗
