### ISSUE TITLE
ps25.7无法激活

### ISSUE THREAD

**Issue by tctiger** [QiuChenlyOpenSource/91QiuChen#57]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

测试发现photoshop 25.7无法激活

### 最小复现

打开软件，运行后，软件崩溃

### 系统情况

- [ ] SIP 是否启动
- [X] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS:Mac OS 14.4.1 
CPU:intel i7 10700k
内存：64G
```

### 是否修改了nvram的内核启动参数（黑苹果）

没有修改

### 是否使用了需要修改系统文件的工具（黑苹果）

没有

### 期望行为

希望能激活PhotoShop 25.7

### Crash Log

[ps.md](https://github.com/QiuChenlyOpenSource/91QiuChen/files/15157426/ps.md)

**Comment by QiuChenly** [comment]
你使用的最新的库注入的吗？

**Comment by tctiger** [comment]
是的

在 2024-04-30 11:32:49，"秋城落叶" ***@***.***> 写道：


你使用的最新的库注入的吗？

**Comment by TrustDec** [comment]
同样的问题🙋

**Comment by QiuChenly** [comment]
进Telegram群组反馈问题吧，这里不好调试

**Comment by tctiger** [comment]
感謝，這幾天太忙了，忙過這幾天再測試，謝謝！



在 2024-05-10 08:41:48，"秋城落叶" ***@***.***> 写道：

进Telegram群组反馈问题吧，这里不好调试

**Comment by QiuChenly** [comment]
Intel 最新版已修复。
ARM版本没有适配。
