### ISSUE TITLE
就是关于黑苹果的，我在使用这个脚本的过程中遇到了一个问题

### ISSUE THREAD

**Issue by abandon17** [QiuChenlyOpenSource/91QiuChen#59]
抱歉打扰了哈，因为我用的是amd黑苹果，然后需要使用amdfriend对Adobe的产品修复才能防止软件崩溃打不开，然后修复的命令行是这样的:
sudo amdfriend --in-place --sign --directories （空格把软件拉进来）
这个项目的地址是这里
https://github.com/NyaomiDEV/AMDFriend
但是我修复以后再使用你的脚本会出现pr和me打开的时候出现app已损坏，请问下是两个脚本有冲突吗？

**Comment by QiuChenly** [comment]
不知道。
