### ISSUE TITLE
Add additional check for app exist

### ISSUE THREAD

**Issue by Drovosek01** [QiuChenlyOpenSource/91QiuChen#62]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

I deleted the After Effects app, but I didn't completely delete it.
The application remains (more precisely, the folder with the extension .app) and only the Contents and Frameworks folder remains inside it

I launched the QiuChenly injection patcher and it crashed while analyzing After Effects

Yes, it's my fault that I didn't completely (incorrectly) delete After Effects, but I think it would be better if your tool checks the existence of files and it won't crash if some files are missing

<img width="1062" alt="Screenshot 2024-05-09 at 20 20 14" src="https://github.com/QiuChenlyOpenSource/91QiuChen/assets/29478700/95a750d4-18f0-40b8-aa50-0d58cc91e7d6">

### 最小复现

1. Install After Effects from Creative Cloud
2. Delete all folder from After Effects.app except Contents folder
3. Launch file 秋城落叶_启动.command
4. Press "n" until the turn comes to After Effects
5. See crash

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS: macOS Sonoma 14.4.1
Macbook Air M1 16GB
```

### 期望行为

Just notification in terminal response about not fully installed searched application

**Comment by QiuChenly** [comment]
we will add an checking of info.plist  function to fix it.
